spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: v1fxHVZ1+/X/tZSIgj2Tz3owb0pO5JVnsvYoS/GsmC8=
      expiration: 86400000
      refresh-token:
        expiration: 172800000


logging:
  level:
    com:
      nhandn: DEBUG
    org:
      springframework:
        web: INFO
